//! SDKWork HTTP route manifest — declares all business routes for OpenAPI
//! materialization, auth-mode resolution, and contract fallback per
//! `WEB_FRAMEWORK_STANDARD.md` §3–§4.
//!
//! Each `HttpRoute` entry carries the method, path template, tag,
//! operation id, and auth mode. The framework's 18-stage interceptor
//! pipeline uses this manifest to:
//! - Resolve `RouteAuth::Public` vs protected routes (§3.4)
//! - Materialize OpenAPI operations with `x-sdkwork-route-auth` (§3.3 I6)
//! - Drive contract-fallback 404/405 responses (§4)

use sdkwork_web_contract::{
    ApiSurface, HttpRoute, HttpMethod, RateLimitTier,
};
use sdkwork_web_core::HttpRouteManifest;

/// The canonical list of all agentstudio-server HTTP routes.
///
/// Routes are grouped by API surface tag. Health and OpenAPI document
/// routes are `Public`; studio public API routes are `Public` (browser
/// session token is optional); management and internal routes are
/// `DualToken` (basic-auth or browser-session in this control-plane
/// standalone profile).
pub static CLAW_SERVER_ROUTES: &[HttpRoute] = &[
    // ── Health (infrastructure, public) ──────────────────────────────
    HttpRoute::public(
        HttpMethod::Get,
        "/claw/health/live",
        "health",
        "health.live",
    ),
    HttpRoute::public(
        HttpMethod::Get,
        "/claw/health/ready",
        "health",
        "health.ready",
    ),

    // ── Studio public API (app-api surface, public with optional session) ──
    HttpRoute::public(
        HttpMethod::Get,
        "/claw/api/v1/discovery",
        "studio-api",
        "studio.api.discovery",
    ),
    HttpRoute::public(
        HttpMethod::Get,
        "/claw/api/v1/studio/instances",
        "studio-api",
        "studio.instances.list",
    ),
    HttpRoute::public(
        HttpMethod::Post,
        "/claw/api/v1/studio/instances",
        "studio-api",
        "studio.instances.create",
    ),
    HttpRoute::public(
        HttpMethod::Get,
        "/claw/api/v1/studio/instances/{id}",
        "studio-api",
        "studio.instances.get",
    ),
    HttpRoute::public(
        HttpMethod::Put,
        "/claw/api/v1/studio/instances/{id}",
        "studio-api",
        "studio.instances.update",
    ),
    HttpRoute::public(
        HttpMethod::Delete,
        "/claw/api/v1/studio/instances/{id}",
        "studio-api",
        "studio.instances.delete",
    ),
    HttpRoute::public(
        HttpMethod::Post,
        "/claw/api/v1/studio/instances/{id}",
        "studio-api",
        "studio.instances.action",
    ),
    HttpRoute::public(
        HttpMethod::Get,
        "/claw/api/v1/studio/instances/{id}/detail",
        "studio-api",
        "studio.instances.detail",
    ),
    HttpRoute::public(
        HttpMethod::Get,
        "/claw/api/v1/studio/instances/{id}/config",
        "studio-api",
        "studio.instances.config.get",
    ),
    HttpRoute::public(
        HttpMethod::Put,
        "/claw/api/v1/studio/instances/{id}/config",
        "studio-api",
        "studio.instances.config.update",
    ),
    HttpRoute::public(
        HttpMethod::Get,
        "/claw/api/v1/studio/instances/{id}/conversations",
        "studio-api",
        "studio.conversations.list",
    ),
    HttpRoute::public(
        HttpMethod::Put,
        "/claw/api/v1/studio/conversations/{conversationId}",
        "studio-api",
        "studio.conversations.upsert",
    ),
    HttpRoute::public(
        HttpMethod::Delete,
        "/claw/api/v1/studio/conversations/{conversationId}",
        "studio-api",
        "studio.conversations.delete",
    ),
    HttpRoute::public(
        HttpMethod::Get,
        "/claw/api/v1/studio/instances/{id}/kernel-chat/agent-profiles",
        "studio-api",
        "studio.kernel-chat.agent-profiles.list",
    ),
    HttpRoute::public(
        HttpMethod::Get,
        "/claw/api/v1/studio/instances/{id}/kernel-chat/sessions",
        "studio-api",
        "studio.kernel-chat.sessions.list",
    ),
    HttpRoute::public(
        HttpMethod::Post,
        "/claw/api/v1/studio/instances/{id}/kernel-chat/sessions",
        "studio-api",
        "studio.kernel-chat.sessions.create",
    ),
    HttpRoute::public(
        HttpMethod::Get,
        "/claw/api/v1/studio/instances/{id}/kernel-chat/sessions/{sessionId}",
        "studio-api",
        "studio.kernel-chat.sessions.get",
    ),
    HttpRoute::public(
        HttpMethod::Patch,
        "/claw/api/v1/studio/instances/{id}/kernel-chat/sessions/{sessionId}",
        "studio-api",
        "studio.kernel-chat.sessions.patch",
    ),
    HttpRoute::public(
        HttpMethod::Delete,
        "/claw/api/v1/studio/instances/{id}/kernel-chat/sessions/{sessionId}",
        "studio-api",
        "studio.kernel-chat.sessions.delete",
    ),
    HttpRoute::public(
        HttpMethod::Post,
        "/claw/api/v1/studio/instances/{id}/kernel-chat/sessions/{sessionId}",
        "studio-api",
        "studio.kernel-chat.sessions.action",
    ),
    HttpRoute::public(
        HttpMethod::Get,
        "/claw/api/v1/studio/instances/{id}/kernel-chat/sessions/{sessionId}/runs",
        "studio-api",
        "studio.kernel-chat.runs.list",
    ),
    HttpRoute::public(
        HttpMethod::Get,
        "/claw/api/v1/studio/instances/{id}/kernel-chat/sessions/{sessionId}/runs/{runId}",
        "studio-api",
        "studio.kernel-chat.runs.get",
    ),
    HttpRoute::public(
        HttpMethod::Get,
        "/claw/api/v1/studio/instances/{id}/kernel-chat/sessions/{sessionId}/messages",
        "studio-api",
        "studio.kernel-chat.messages.list",
    ),
    HttpRoute::public(
        HttpMethod::Get,
        "/claw/api/v1/studio/instances/{id}/logs",
        "studio-api",
        "studio.instances.logs",
    ),
    HttpRoute::public(
        HttpMethod::Post,
        "/claw/api/v1/studio/instances/{id}/gateway/invoke",
        "studio-api",
        "studio.gateway.invoke",
    ),
    HttpRoute::public(
        HttpMethod::Post,
        "/claw/api/v1/studio/instances/{id}/tasks",
        "studio-api",
        "studio.tasks.create",
    ),
    HttpRoute::public(
        HttpMethod::Put,
        "/claw/api/v1/studio/instances/{id}/tasks/{taskId}",
        "studio-api",
        "studio.tasks.update",
    ),
    HttpRoute::public(
        HttpMethod::Delete,
        "/claw/api/v1/studio/instances/{id}/tasks/{taskId}",
        "studio-api",
        "studio.tasks.delete",
    ),
    HttpRoute::public(
        HttpMethod::Post,
        "/claw/api/v1/studio/instances/{id}/tasks/{taskId}",
        "studio-api",
        "studio.tasks.action",
    ),
    HttpRoute::public(
        HttpMethod::Get,
        "/claw/api/v1/studio/instances/{id}/tasks/{taskId}/executions",
        "studio-api",
        "studio.tasks.executions.list",
    ),
    HttpRoute::public(
        HttpMethod::Put,
        "/claw/api/v1/studio/instances/{id}/files/{fileId}",
        "studio-api",
        "studio.files.update",
    ),
    HttpRoute::public(
        HttpMethod::Put,
        "/claw/api/v1/studio/instances/{id}/llm-providers/{providerId}",
        "studio-api",
        "studio.llm-providers.update",
    ),

    // ── OpenAPI documents (public) ───────────────────────────────────
    HttpRoute::public(
        HttpMethod::Get,
        "/claw/openapi/v1.json",
        "openapi",
        "openapi.native.v1",
    ),
    HttpRoute::public(
        HttpMethod::Get,
        "/claw/openapi/local-ai-compat-v1.json",
        "openapi",
        "openapi.local-ai-compat.v1",
    ),
    HttpRoute::public(
        HttpMethod::Get,
        "/claw/openapi/openclaw-gateway-v1.json",
        "openapi",
        "openapi.openclaw-gateway.v1",
    ),

    // ── Internal node sessions (backend-api, authenticated) ──────────
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/claw/internal/v1/host-platform",
        "internal",
        "internal.host-platform.read",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/claw/internal/v1/node-sessions/hello",
        "internal",
        "internal.node-sessions.hello",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/claw/internal/v1/node-sessions/admit",
        "internal",
        "internal.node-sessions.admit",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/claw/internal/v1/node-sessions/heartbeat",
        "internal",
        "internal.node-sessions.heartbeat",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/claw/internal/v1/node-sessions/pull-desired-state",
        "internal",
        "internal.node-sessions.pull-desired-state",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/claw/internal/v1/node-sessions/ack-desired-state",
        "internal",
        "internal.node-sessions.ack-desired-state",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/claw/internal/v1/node-sessions/close",
        "internal",
        "internal.node-sessions.close",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/claw/internal/v1/node-sessions",
        "internal",
        "internal.node-sessions.list",
    ),

    // ── Management API (backend-api, authenticated) ──────────────────
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/claw/manage/v1/rollouts",
        "manage",
        "manage.rollouts.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/claw/manage/v1/rollouts/preview",
        "manage",
        "manage.rollouts.preview",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/claw/manage/v1/rollouts/start",
        "manage",
        "manage.rollouts.start",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/claw/manage/v1/host-endpoints",
        "manage",
        "manage.host-endpoints.read",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/claw/manage/v1/openclaw/runtime",
        "manage",
        "manage.openclaw.runtime.read",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/claw/manage/v1/openclaw/gateway",
        "manage",
        "manage.openclaw.gateway.read",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/claw/manage/v1/openclaw/gateway/invoke",
        "manage",
        "manage.openclaw.gateway.invoke",
    )
    .with_rate_limit_tier(RateLimitTier::Internal),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/claw/manage/v1/service/status",
        "manage",
        "manage.service.status",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/claw/manage/v1/service/install",
        "manage",
        "manage.service.install",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/claw/manage/v1/service/start",
        "manage",
        "manage.service.start",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/claw/manage/v1/service/stop",
        "manage",
        "manage.service.stop",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/claw/manage/v1/service/restart",
        "manage",
        "manage.service.restart",
    ),

    // ── OpenClaw gateway proxy (public proxy, rate-limited) ──────────
    HttpRoute::public(
        HttpMethod::Post,
        "/claw/gateway/openclaw/tools/invoke",
        "gateway",
        "gateway.openclaw.tools.invoke",
    )
    .with_rate_limit_tier(RateLimitTier::Internal),
];

/// Build the `HttpRouteManifest` from the static route list.
pub fn claw_server_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(CLAW_SERVER_ROUTES)
}

/// Infer the API surface for a given path (used by the framework pipeline).
#[allow(dead_code)]
pub fn infer_surface(path: &str) -> ApiSurface {
    sdkwork_web_contract::infer_api_surface_from_path(path)
}
