pub mod bundled;
pub mod capabilities;
pub mod components;
pub mod config;
pub mod context;
pub mod desktop_host_bootstrap;
pub mod dialog;
pub mod embedded_host_server;
pub mod error;
pub mod events;
pub mod filesystem;
pub mod install_records;
pub mod kernel;
pub mod kernel_host;
pub mod kernel_runtime;
pub mod layout;
pub mod logging;
pub mod openclaw_release;
pub mod paths;
pub mod ports;
pub mod policy;
pub mod runtime;
pub mod services;
pub mod storage;

pub use error::{FrameworkError, Result};
