services:
  agentstudio-server:
    env_file:
      - profiles/default.env
      - profiles/nvidia-cuda.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]
