export type {
  PlatformAPI,
  PlatformCapturedScreenshot,
  PlatformDialogFilter,
  PlatformFetchedRemoteUrl,
  PlatformFileEntry,
  PlatformNotificationRequest,
  PlatformPathInfo,
  PlatformSaveFileOptions,
  PlatformSelectFileOptions,
  PlatformWindowStateUnsubscribe,
} from './types.ts';
export type {
  HostPlatformLifecycle,
  HostPlatformMode,
  HostPlatformStateStoreAvailability,
  HostPlatformStateStoreProjectionMode,
  HostPlatformStateStoreProfileRecord,
  HostPlatformStateStoreProviderRecord,
  HostPlatformStateStoreRecord,
  HostPlatformStatusRecord,
  InternalErrorEnvelope,
  InternalNodeCompatibilityState,
  InternalNodeSessionRecord,
  InternalNodeSessionState,
  InternalPlatformAPI,
} from './contracts/internal.ts';
export type {
  KernelPlatformAPI,
  RuntimeDesktopKernelControlSocketInfo,
  RuntimeDesktopKernelControlSocketKind,
  RuntimeDesktopKernelEndpointInfo,
  RuntimeDesktopKernelEndpointSource,
  RuntimeDesktopKernelHealthStatus,
  RuntimeDesktopKernelHostInfo,
  RuntimeDesktopKernelHostServiceInfo,
  RuntimeDesktopKernelInstallSource,
  RuntimeKernelPreflightOutcome,
  RuntimeDesktopKernelOwnershipMode,
  RuntimeDesktopKernelProvenanceInfo,
  RuntimeDesktopKernelRuntimeState,
  RuntimeDesktopKernelRuntimeStatusInfo,
  RuntimeDesktopKernelServiceManagerKind,
  RuntimeDesktopKernelTopologyInfo,
  RuntimeDesktopKernelTopologyKind,
  RuntimeDesktopKernelTopologyState,
} from './contracts/kernel.ts';
export type {
  ComponentPlatformAPI,
  KnownRuntimeBundledComponentId,
  RuntimeBundledComponentId,
  RuntimeDesktopComponentCapabilityInfo,
  RuntimeDesktopComponentCatalogInfo,
  RuntimeDesktopComponentKind,
  RuntimeDesktopComponentLifecycle,
  RuntimeDesktopComponentControlAction,
  RuntimeDesktopComponentControlRequest,
  RuntimeDesktopComponentControlResult,
  RuntimeDesktopComponentDocumentationRef,
  RuntimeDesktopComponentEndpointInfo,
  RuntimeDesktopComponentInfo,
  RuntimeDesktopComponentRuntimeStatus,
  RuntimeDesktopComponentServiceBindingInfo,
  RuntimeDesktopComponentStartupMode,
} from './contracts/components.ts';
export type {
  InstallAssessmentCheckType,
  InstallAssessmentCommand,
  InstallAssessmentDataItem,
  InstallAssessmentDataItemKind,
  InstallAssessmentDataUninstallPolicy,
  InstallAssessmentDependency,
  InstallAssessmentDependencyStatus,
  InstallAssessmentInstallation,
  InstallAssessmentInstallationDirectories,
  InstallAssessmentInstallationDirectory,
  InstallAssessmentInstallationMethod,
  InstallAssessmentIssue,
  InstallAssessmentMethodType,
  InstallAssessmentMigrationMode,
  InstallAssessmentMigrationStrategy,
  InstallAssessmentResult,
  InstallAssessmentRuntime,
  InstallAssessmentSeverity,
  InstallAssessmentShellKind,
  InstallCatalogEntry,
  InstallCatalogHostPlatform,
  InstallCatalogQuery,
  InstallCatalogRuntimePlatform,
  InstallCatalogVariant,
  InstallArtifactReport,
  InstallContainerRuntimePreference,
  InstallControlLevel,
  InstallDependencyReport,
  InstallDependencyRequest,
  InstallDependencyResult,
  InstallPlatform,
  InstallProgressEvent,
  InstallProgressOperationKind,
  InstallProgressStream,
  InstallRecordStatus,
  InstallRequest,
  InstallResolvedContainerRuntime,
  InstallResult,
  InstallScope,
  InstallStageReport,
  UninstallRequest,
  UninstallResult,
  UninstallTarget,
  UninstallTargetReport,
  UninstallTargetStatus,
  InstallerPlatformAPI,
} from './contracts/installer.ts';
export type {
  ManagePlatformAPI,
  ManageHostEndpointRecord,
  ManageOpenClawGatewayInvokeRequest,
  ManageOpenClawGatewayRecord,
  ManageOpenClawRuntimeRecord,
  ManageRolloutCandidateRevisionSummary,
  ManageRolloutListResult,
  ManageRolloutPhase,
  ManageRolloutPreview,
  ManageRolloutPreviewSummary,
  ManageRolloutRecord,
  ManageRolloutTargetPreviewRecord,
  PreviewRolloutRequest,
} from './contracts/manage.ts';
export type {
  RuntimeAppInfo,
  RuntimeConfigInfo,
  RuntimeDesktopBundledComponentInfo,
  RuntimeDesktopBundledComponentsInfo,
  RuntimeDesktopFilesystemInfo,
  RuntimeDesktopOpenClawChannelConfigHealthInfo,
  RuntimeDesktopOpenClawRuntimeInfo,
  RuntimeDesktopIntegrationInfo,
  RuntimeDesktopIntegrationAdapterInfo,
  RuntimeDesktopActiveKernelRuntimeInfo,
  RuntimeDesktopKernelInfo,
  RuntimeDesktopLocalAiProxyInfo,
  RuntimeDesktopNotificationInfo,
  RuntimeDesktopNotificationProviderInfo,
  RuntimeDesktopPaymentInfo,
  RuntimeDesktopPaymentProviderInfo,
  RuntimeDesktopPermissionInfo,
  RuntimeDesktopPermissionsInfo,
  RuntimeDesktopPermissionStatus,
  RuntimeDesktopProviderAvailability,
  RuntimeDesktopProcessInfo,
  RuntimeDesktopProcessProfileInfo,
  RuntimeDesktopSecurityInfo,
  RuntimeBuiltInOpenClawStatusChangedEvent,
  RuntimeEventUnsubscribe,
  RuntimeInfo,
  RuntimeJobRecord,
  RuntimeJobState,
  RuntimeJobUpdateEvent,
  RuntimeDistributionFamily,
  RuntimeDeploymentFamily,
  RuntimeAcceleratorProfile,
  RuntimeLanguagePreference,
  RuntimePathsInfo,
  RuntimePlatformKind,
  RuntimePlatformAPI,
  RuntimeProcessOutputEvent,
  RuntimeProcessOutputStream,
  RuntimeStartupContext,
  RuntimeStorageInfo,
  RuntimeSystemInfo,
} from './contracts/runtime.ts';
export type {
  StorageDeleteRequest,
  StorageDeleteResult,
  StorageGetTextRequest,
  StorageGetTextResult,
  StorageListKeysRequest,
  StorageListKeysResult,
  StoragePlatformAPI,
  StoragePlatformInfo,
  StoragePutTextRequest,
  StoragePutTextResult,
} from './contracts/storage.ts';
export type {
  StudioCreatedKernelAgentRecord,
  StudioCreateKernelAgentInput,
  StudioKernelAgentCreationCapability,
  StudioKernelAgentCreationFieldSupport,
  StudioKernelAgentCreationKernelOption,
  StudioKernelAgentCreationModelOption,
  StudioKernelAgentCreationReasonCode,
  StudioCreateKernelChatSessionInput,
  StudioCreateInstanceInput,
  StudioInstanceTaskMutationPayload,
  StudioOpenClawGatewayInvokeOptions,
  StudioOpenClawGatewayInvokeRequest,
  StudioPatchKernelChatSessionInput,
  StudioPlatformAPI,
  StudioStartKernelChatRunInput,
  StudioUpdateInstanceLlmProviderConfigInput,
  StudioUpdateInstanceInput,
} from './contracts/studio.ts';
export type {
  KernelChatAgentProfile,
  KernelChatMessage,
  KernelChatRun,
  KernelChatSession,
  PersistedKernelChatAgentRecord,
  LocalAiProxyLoggedMessage,
  LocalAiProxyMessageCaptureSettings,
  LocalAiProxyMessageLogRecord,
  LocalAiProxyMessageLogsQuery,
  OpenClawMirrorComponentKind,
  OpenClawMirrorComponentRecord,
  OpenClawMirrorExportPreview,
  OpenClawMirrorExportRequest,
  OpenClawMirrorExportResult,
  OpenClawMirrorImportPreview,
  OpenClawMirrorImportRequest,
  OpenClawMirrorImportResult,
  OpenClawMirrorManifestComponentRecord,
  OpenClawMirrorManifestRecord,
  OpenClawMirrorManifestRuntimeRecord,
  OpenClawMirrorMode,
  OpenClawMirrorRuntimeRecord,
  OpenClawMirrorSafetySnapshotRecord,
  LocalAiProxyRequestLogRecord,
  LocalAiProxyRequestLogsQuery,
  LocalAiProxyRequestLogStatus,
  LocalAiProxyRouteTestRecord,
  PaginatedResult,
  StudioConversationRecord,
  StudioInstanceDetailRecord,
  StudioInstanceConfig,
  StudioInstanceRecord,
  StudioWorkbenchTaskExecutionRecord,
} from '@sdkwork/agentstudio-pc-types';
export {
  STABLE_BUILT_IN_OPENCLAW_INSTANCE_ID,
  canonicalizeBuiltInOpenClawInstanceId,
  isBuiltInOpenClawInstanceId,
  matchesBuiltInOpenClawInstanceId,
} from '@sdkwork/agentstudio-pc-types';
export {
  components,
  configurePlatformBridge,
  getComponentPlatform,
  getInternalPlatform,
  getInstallerPlatform,
  getKernelPlatform,
  getManagePlatform,
  getPlatformBridge,
  getRuntimePlatform,
  getStoragePlatform,
  getStudioPlatform,
  internal,
  installer,
  kernel,
  manage,
  platform,
  runtime,
  STUDIO_DETAIL_CACHE_TTL_MS,
  storage,
  studio,
} from './registry.ts';
export {
  BUNDLED_COMPONENT_IDS,
  componentLibrary,
  createDesktopComponentLibrary,
  DesktopComponentLibrary,
  isBundledComponentId,
} from './componentLibrary.ts';
export { openExternalUrl } from './openExternalUrl.ts';
export { openDiagnosticPath } from './openDiagnosticPath.ts';
export { WebComponentPlatform } from './webComponents.ts';
export {
  bootstrapServerBrowserPlatformBridge,
  configureServerBrowserPlatformBridge,
  createServerBrowserPlatformBridge,
  readServerBrowserPlatformBridgeConfig,
  SERVER_ACCELERATOR_PROFILE_META_NAME,
  SERVER_API_BASE_PATH_META_NAME,
  SERVER_BROWSER_BOOTSTRAP_DESCRIPTOR_PATH,
  SERVER_DEPLOYMENT_FAMILY_META_NAME,
  SERVER_DISTRIBUTION_FAMILY_META_NAME,
  SERVER_HOST_MODE_META_NAME,
  SERVER_INTERNAL_BASE_PATH_META_NAME,
  SERVER_MANAGE_BASE_PATH_META_NAME,
  type ConfigureServerBrowserPlatformBridgeOptions,
  type ServerBrowserBridgeDocumentLike,
  type ServerBrowserPlatformBridgeConfig,
} from './serverBrowserBridge.ts';
export { WebInternalPlatform, DEFAULT_INTERNAL_BASE_PATH } from './webInternal.ts';
export { WebKernelPlatform } from './webKernel.ts';
export { WebManagePlatform, DEFAULT_MANAGE_BASE_PATH } from './webManage.ts';
export { WebPlatform } from './web.ts';
export { WebHostedStudioPlatform, DEFAULT_STUDIO_API_BASE_PATH } from './webHostedStudio.ts';
export { WebStoragePlatform } from './webStorage.ts';
