import {
  resolveChatWorkspacePresentation,
} from '../services';
import type {
  ChatPageSourceState,
  ChatPageUiState,
  ChatPageTranslate,
  ChatPageWorkspaceState,
} from './chatPageContracts';
import { useChatContextCatalogState } from './useChatContextCatalogState';
import { useChatInteractionState } from './useChatInteractionState';
import { useChatModelCatalogState } from './useChatModelCatalogState';
import { useChatPageRuntimeState } from './useChatPageRuntimeState';
import { useChatSessionViewState } from './useChatSessionViewState';

export interface UseChatPageWorkspaceStateInput {
  t: ChatPageTranslate;
  sourceState: ChatPageSourceState;
  pageUiState: Pick<ChatPageUiState, 'drawer' | 'selection'>;
}

export function useChatPageWorkspaceState({
  t,
  sourceState,
  pageUiState,
}: UseChatPageWorkspaceStateInput): ChatPageWorkspaceState {
  const {
    instance: instanceSource,
    runtime: runtimeSource,
    modelPreference: modelPreferenceSource,
  } = sourceState;
  const {
    activeInstanceId,
  } = instanceSource;
  const {
    sessions,
    activeSessionIdByInstance,
    syncStateByInstance,
    gatewayConnectionStatusByInstance,
    lastErrorByInstance,
    instanceRouteModeById,
    instanceChatAdapterCapabilitiesById,
    createSession,
    addMessage,
    updateMessage,
    removeMessages,
    flushSession,
    sendKernelMessage,
    abortSession,
    setKernelSessionModel,
    setKernelSessionThinkingLevel,
    setKernelSessionFastMode,
    setKernelSessionVerboseLevel,
    setKernelSessionReasoningLevel,
  } = runtimeSource;
  const {
    setActiveChannel,
    setActiveModel,
    activeChannelId,
    activeModelId,
  } = modelPreferenceSource;
  const {
    drawer,
    selection,
  } = pageUiState;
  const { isSessionContextDrawerOpen } = drawer;
  const { selectedAgentId, selectedSkillId } = selection;
  const {
    activeSessionId,
    syncState,
    routeMode,
    lastError,
    activeAdapterCapabilities,
    isChatSupportedRoute,
    agentCatalogMode,
    sessionScopeMode,
    sendMode,
    newSessionModelMode,
    supportsSessionScopeSync,
    gatewayConnectionStatus,
  } = useChatPageRuntimeState({
    activeInstanceId,
    activeSessionIdByInstance,
    syncStateByInstance,
    gatewayConnectionStatusByInstance,
    lastErrorByInstance,
    instanceRouteModeById,
    instanceChatAdapterCapabilitiesById,
  });
  const {
    defaultAgentId,
    effectiveGatewayAgentId,
    hasResolvedVisibleAgents,
    visibleAgentIds,
    isAgentSelectorLoading,
    isSkillSelectorLoading,
    agentOptions,
    skillOptions,
    visibleAgents,
    activeAgent,
    activeSkill,
  } = useChatContextCatalogState({
    t,
    sessions,
    activeInstanceId,
    activeSessionId,
    isChatSupportedRoute,
    agentCatalogMode,
    isSessionContextDrawerOpen,
    selectedAgentId,
    selectedSkillId,
  });
  const {
    workspaceMode,
    isExplicitBlankWorkspace,
    isDisplaySessionFallback,
    selectableInstanceSessions,
    selectedSession,
    displaySessionId,
    displaySession,
    activeKernelSessionState,
    activeRunBinding,
    chatRuntimeState,
    isUnsupportedRoute,
    runningRunBinding,
    sessionSelectedModelId,
    activeMessages,
    conversationBodyState,
    activeMessageGroups,
  } = useChatSessionViewState({
    sessions,
    activeInstanceId,
    activeSessionId,
    isChatSupportedRoute,
    sessionScopeMode,
    effectiveGatewayAgentId,
    routeMode,
    activeAdapterCapabilities,
    sendMode,
  });
  const {
    modelCatalog,
    modelCatalogError,
    catalogChannels,
  } = useChatModelCatalogState({
    activeInstanceId,
    isChatSupportedRoute,
    effectiveGatewayAgentId,
    agentCatalogMode,
  });
  const {
    isActiveSessionGenerating,
    isBusy,
    canStop,
    channels,
    activeChannel,
    activeModel,
    sessionControlActions,
    activeThinkingLevel,
    thinkingLevelDefaultLabel,
    thinkingLevelOptions,
    activeFastMode,
    fastModeDefaultLabel,
    fastModeOptions,
    activeVerboseLevel,
    verboseLevelDefaultLabel,
    verboseLevelOptions,
    activeReasoningLevel,
    reasoningLevelDefaultLabel,
    reasoningLevelOptions,
    newSessionModel,
    handleChannelChange,
    handleModelChange,
    handleSend,
    handleStop,
  } = useChatInteractionState({
    t,
    activeInstanceId,
    selectedSessionId: activeSessionId,
    displaySessionId,
    sessionControlSessionId:
      isDisplaySessionFallback ? null : selectedSession?.id ?? null,
    activeKernelSessionState,
    activeRunBinding,
    runningRunBinding,
    sendMode,
    catalogChannels,
    sessionSelectedModelId,
    activeChannelId,
    activeModelId,
    routeMode,
    isChatSupportedRoute,
    activeAdapterCapabilities,
    newSessionModelMode,
    effectiveGatewayAgentId,
    activeSkill,
    activeAgent,
    sessionScopeMode,
    createSession,
    addMessage,
    updateMessage,
    removeMessages,
    flushSession,
    sendKernelMessage,
    abortSession,
    setActiveChannel,
    setActiveModel,
    setKernelSessionModel,
    setKernelSessionThinkingLevel,
    setKernelSessionFastMode,
    setKernelSessionVerboseLevel,
    setKernelSessionReasoningLevel,
  });
  const {
    primaryAgentId,
    sidebarAgentOptions,
    selectedWorkspaceAgentName,
    workspaceTitle,
  } = resolveChatWorkspacePresentation({
    sessionScopeMode,
    defaultAgentId,
    visibleAgents,
    effectiveGatewayAgentId,
    activeAgentName: activeAgent?.name ?? null,
    mainAgentLabel: t('chat.sidebar.mainAgent'),
    workspaceMode,
    isExplicitBlankWorkspace,
    hasDisplaySession: Boolean(displaySession),
  });

  return {
    runtime: {
      activeSessionId,
      syncState,
      routeMode,
      lastError,
      activeAdapterCapabilities,
      isChatSupportedRoute,
      agentCatalogMode,
      sessionScopeMode,
      sendMode,
      newSessionModelMode,
      supportsSessionScopeSync,
      gatewayConnectionStatus,
      defaultAgentId,
      effectiveGatewayAgentId,
      hasResolvedVisibleAgents,
      visibleAgentIds,
    },
    catalog: {
      isAgentSelectorLoading,
      isSkillSelectorLoading,
      agentOptions,
      skillOptions,
      visibleAgents,
      activeAgent,
      activeSkill,
      modelCatalog,
      modelCatalogError,
      catalogChannels,
    },
    session: {
      workspaceMode,
      isExplicitBlankWorkspace,
      isDisplaySessionFallback,
      selectableInstanceSessions,
      selectedSession,
      displaySessionId,
      displaySession,
      activeKernelSessionState,
      activeRunBinding,
      chatRuntimeState,
      isUnsupportedRoute,
      runningRunBinding,
      sessionSelectedModelId,
      activeMessages,
      conversationBodyState,
      activeMessageGroups,
    },
    interaction: {
      isActiveSessionGenerating,
      isBusy,
      canStop,
      channels,
      activeChannel,
      activeModel,
      sessionControlActions,
      activeThinkingLevel,
      thinkingLevelDefaultLabel,
      thinkingLevelOptions,
      activeFastMode,
      fastModeDefaultLabel,
      fastModeOptions,
      activeVerboseLevel,
      verboseLevelDefaultLabel,
      verboseLevelOptions,
      activeReasoningLevel,
      reasoningLevelDefaultLabel,
      reasoningLevelOptions,
      newSessionModel,
      handleChannelChange,
      handleModelChange,
      handleSend,
      handleStop,
    },
    presentation: {
      primaryAgentId,
      sidebarAgentOptions,
      selectedWorkspaceAgentName,
      workspaceTitle,
    },
  };
}
